// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenFilesWithErrors
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenFilesWithErrors.761e0615-1d7d-48f7-8431-e9e53a0c1735";
        public const string Name = "OpenFilesWithErrors";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Peter Ritchie";
        public const string Tags = "";
    }
}
