// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace OpenFilesWithErrors
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OpenFilesWithErrorsString = "1422d4e3-21bc-40d5-8890-efce0da1b09a";
        public static Guid OpenFilesWithErrors = new Guid(OpenFilesWithErrorsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int OpenFilesWithErrorsCommand = 0x0100;
    }
}
